### ISSUE TITLE
Autowalk/Baritone crashing the game

### ISSUE THREAD

**Issue by bextoper** [kami-blue/client#1022]
If you're ;b goto 'coords' and then try to use autowalk forward (not sure about other types of autowalk), game will crash.
Kami Blue 1.1.7 eca19025
Crash Report Below
-------------------------

---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-1.1.7-eca19025-release.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7/7/20 9:31 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.zeroeightsix.kami.module.modules.movement.AutoWalk.getHudInfo(AutoWalk.kt:85)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.lambda$renderComponent$0(KamiActiveModulesUI.java:39)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI$$Lambda$404/1456474438.apply(Unknown Source)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.Comparator$$Lambda$80/241386206.compare(Unknown Source)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.renderComponent(KamiActiveModulesUI.java:40)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.renderComponent(KamiActiveModulesUI.java:27)
	at me.zeroeightsix.kami.gui.rgui.component.container.AbstractContainer.renderChildren(AbstractContainer.java:80)
	at me.zeroeightsix.kami.gui.UIRenderer.renderAndUpdateFrames(UIRenderer.java:57)
	at me.zeroeightsix.kami.event.ForgeEventProcessor.onRender(ForgeEventProcessor.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_ForgeEventProcessor_onRender_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:609)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:169)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zeroeightsix.kami.module.modules.movement.AutoWalk.getHudInfo(AutoWalk.kt:85)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.lambda$renderComponent$0(KamiActiveModulesUI.java:39)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI$$Lambda$404/1456474438.apply(Unknown Source)
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469)
	at java.util.Comparator$$Lambda$80/241386206.compare(Unknown Source)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.renderComponent(KamiActiveModulesUI.java:40)
	at me.zeroeightsix.kami.gui.kami.theme.kami.KamiActiveModulesUI.renderComponent(KamiActiveModulesUI.java:27)
	at me.zeroeightsix.kami.gui.rgui.component.container.AbstractContainer.renderChildren(AbstractContainer.java:80)
	at me.zeroeightsix.kami.gui.UIRenderer.renderAndUpdateFrames(UIRenderer.java:57)
	at me.zeroeightsix.kami.event.ForgeEventProcessor.onRender(ForgeEventProcessor.java:187)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_ForgeEventProcessor_onRender_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:609)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:169)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['bextoper'/15138684, l='MpServer', x=-15743.38, y=120.00, z=-15743.38]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 153210 game time, 2173869859 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['bextoper'/15138684, l='MpServer', x=-15743.38, y=120.00, z=-15743.38]]
	Retry entities: 0 total; []
	Server brand: Waterfall (git:Waterfall-Bootstrap:1.15-SNAPSHOT:2615829:346) <- 2b2t
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 313485248 bytes (298 MB) / 805306368 bytes (768 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version         | Source                              | Signature                                |
	|:------ |:--------- |:--------------- |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2          | minecraft.jar                       | None                                     |
	| LCHIJA | mcp       | 9.42            | minecraft.jar                       | None                                     |
	| LCHIJA | FML       | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | kamiblue  | v1.1.7-eca19025 | kamiblue-1.1.7-eca19025-release.jar | None                                     |
	| LCHIJA | forgelin  | 1.8.4           | kamiblue-1.1.7-eca19025-release.jar | None                                     |

	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-1.1.7-eca19025-release.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 446.14' Renderer: 'GeForce GTX 1660/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/NewDefault+v1.26[MC1.15+]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

**Comment by dominikaaaa** [comment]
This has already been reported, #1014

Also, ffs please do something about your formatting, it's horrible
