### ISSUE TITLE
OffhandGap Recursive Problem

### ISSUE THREAD

**Issue by iBuyMountainDew** [kami-blue/client#1076]
**Describe the bug**
Recursive problem with OffhandGap?

**Comment by iBuyMountainDew** [comment]
`at me.zeroeightsix.kami.module.modules.combat.OffhandGap.moveGapsToInventory(OffhandGap.java:151)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.moveGapsWaitForNoGui(OffhandGap.java:158)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.disableGaps(OffhandGap.java:136)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.lambda$new$4(OffhandGap.java:67)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap$$Lambda$289/2094246806.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$346/1319354475.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at net.minecraft.network.NetworkManager.handler$onSendPacket$zbi000(NetworkManager.java:542)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:567)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.moveGapsToInventory(OffhandGap.java:151)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.moveGapsWaitForNoGui(OffhandGap.java:158)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.disableGaps(OffhandGap.java:136)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.lambda$new$4(OffhandGap.java:67)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap$$Lambda$289/2094246806.invoke(Unknown Source)
	at me.zero.alpine.listener.Listener.invoke(Listener.java:93)
	at me.zero.alpine.EventManager.lambda$post$5(EventManager.java:91)
	at me.zero.alpine.EventManager$$Lambda$346/1319354475.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at me.zero.alpine.EventManager.post(EventManager.java:91)
	at net.minecraft.network.NetworkManager.handler$onSendPacket$zbi000(NetworkManager.java:542)
	at net.minecraft.network.NetworkManager.func_179290_a(NetworkManager.java)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147297_a(NetHandlerPlayClient.java:805)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:567)
	at me.zeroeightsix.kami.module.modules.combat.OffhandGap.moveGapsToInventory(OffhandGap.java:151)`

**Comment by dominikaaaa** [comment]
Being rewritten atm
