### ISSUE TITLE
Minecraft freezes at start while loading kami-blue xray block

### ISSUE THREAD

**Issue by zihasz** [kami-blue/client#1096]
**Describe the bug**
When I start Minecraft the game starts loading fine but when it gets to loading item renderer it freezes.

**To Reproduce**
N/A

**Expected behaviour**
I expect Minecraft to start

**Screenshots**
https://gyazo.com/428c21c28447cef7d7b04c0130e55a19

**Additional context**
*Logs*
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at me.zeroeightsix.kami.KamiMod.saveConfigurationUnsafe(KamiMod.java:240) ~[KamiMod.class:?]
	at me.zeroeightsix.kami.KamiMod.saveConfiguration(KamiMod.java:232) ~[KamiMod.class:?]
	at net.minecraft.client.Minecraft.save(Minecraft.java:3427) ~[bib.class:?]
	at net.minecraft.client.Minecraft.handler$displayCrashReport$zbe000(Minecraft.java:3415) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
*Mods*
1.12.2-Ghostwriter-1.9.8.jar
AppleSkin-mc1.12-1.0.9.jar
Impact-4.9.1-1.12.2.jar
KAMI-Blue-v1.1.6-release.jar
reauth-3.6.0.jar
salhack-github-2.05-release.jar
seppuku-3.0.5.jar
*Other*
Cant use optifine because it crashes.

**Comment by dominikaaaa** [comment]
I need the log file, and it does not freeze because of loading the x-ray blocks.

**Comment by zihasz** [comment]
Its fixed now
