### ISSUE TITLE
MidClickPearl crashes when used on a ladder

### ISSUE THREAD

**Issue by dominikaaaa** [kami-blue/client#1242]
This is related to #1175

MidClickPearl line that crashed:

```kotlin
        if (mc.player == null || mc.objectMouseOver.typeOfHit == RayTraceResult.Type.BLOCK) return@EventHook
```

SelectionHighlight line that crashed:
```kotlin
        if (block.value && hitObject.typeOfHit == Type.BLOCK) {
```

Full log:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-1.1.7-319ba9a6-release.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 8/23/20 7:34 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at me.zeroeightsix.kami.module.modules.combat.MidClickPearl$mouseListener$1.invoke(MidClickPearl.kt:32)
	at me.zeroeightsix.kami.module.modules.combat.MidClickPearl$mouseListener$1.invoke(MidClickPearl.kt:26)
```

**Comment by Xiaro** [comment]
Closed in 81f22f6
