### ISSUE TITLE
Upgraded from v1.1.7-dde7f7b7 to v1.1.7-b2448f04, all KAMI/blue modules were disabled.

### ISSUE THREAD

**Issue by HoratioGamer** [kami-blue/client#1416]
**Describe the bug**
I do not know what the bug is.   
I am using linux,MultiMC,and have a subdirectory in my instances/1.12.2/mods/Old Kami  where I put my old downloads of KAMI/Blue jars when I get the new jar from the Kami/Blue discord.  

**To Reproduce**

These are the steps that occurred.   

1. at [21:15:36] last night I was using KAMI/Blue v1.1.7-dde7f7b7 in 2b2t.   The server kicked me at the end of 6 hours of login time.   I exited minecraft by clicking the X on the top corner of the window.   

2. I made some posts in Discord.

. I checked for a new KAMI/Blue at about 21:40 found that there was a new one v1.1.7-b2448f04 and saved into both my 2B2T (1.12.2) instance and my OldFag-1.12.2 instance on MultiMC.   

4. I used the Ubuntu file manager to navigate to those two directories and I moved the old .jar into the Old Kami directory.

5. I never touched the computer until the next day 

6. At 05:33:21, I started the 1.12.2 instance of minecraft, and entered the Q for 2B2T.  I started my latest.log monitoring script that helps me predict on-line times from queue progression.    I do not recall if the Kami module list appeared on the screen at this time.  After a few minutes, it was predicting a time that was too early so I killed that instance of minecraft with the X in the top corner of the Ubuntu window.  

7. I restarted the 1.12.2 instance of minecraft, and seconds later at At 05:43:24, my latest.log monitoring script.   By 05:52:04 I was getting on-line prediction times of about 07:15 which I know from experience to be as much as an hour optimistic, but acceptable so I did other things.   At no time did I edit either the configuration of KAMI/Blue or touch the config files.

8. At 08:22:20 I entered 2b2t.  I played normally.  I took a number of screen shots during this period before realizing all of the Kami/Blue modules were shut off, these screenshots show no modules listed, and the KAMI dashboard is not visible.     

8. I was doing normal road work, which involved a lot of running.  Eventually I noticed, I was getting hungry... I thought, OK Hause patched AntiHunger again.   I looked up and realized there were no Kami/Blue modules listed.   

9. I pressed Y to open the KAMI/Blue interface.  All of the pop-up menus were open, and arranged in a different pattern (a neater pattern actually) than I was used to.   I found this odd.   I struggled to remember all of the KAMI/Blue modules I had active.  I knew automatic logout and AntiHunger were two that I really wanted and set those.   I then had to call up an old screen shot and find my list of KAMI/Blue modules from last night.   I replicated them.  One of the modules was FastBreak, that last night I had had to set the delay to 5.0, it was back to zero again.  This time I set it to 4.0.   

10.  I re-started my road building and made a report in the KAMI/Blue Discord.

11.  I was told it was not possible, and that I must submit a bug report. 

**Expected behavior**

The expected behaviour is that configurations persist from one jar upgrade to another.

**Screenshots**
One of the last screenshots from last night.  
![2020-10-04_20 44 20](https://user-images.githubusercontent.com/69666047/95105194-cae1ee80-0704-11eb-8cfb-745833f84742.png)

The first screenshot from this morning... note the module list and KAMI/Blue dashboard are not there.
![2020-10-05_08 25 18](https://user-images.githubusercontent.com/69666047/95105212-d33a2980-0704-11eb-980a-40ab6e78c913.png)

Screenshots of the directory listings of my mods, Old Kami and .minecraft directory.   

![Kami1](https://user-images.githubusercontent.com/69666047/95105838-b81be980-0705-11eb-949a-ca6b40d2d21c.jpg)
![Kami2](https://user-images.githubusercontent.com/69666047/95105842-b8b48000-0705-11eb-8b73-a51b69a88b84.jpg)
![Kami3](https://user-images.githubusercontent.com/69666047/95105843-b8b48000-0705-11eb-941c-31ed7622cad0.jpg)

** Log file lines that might be interesting **

From the first run of minecraft this morning (only the KAMI lines):

[05:31:06] [Client thread/INFO] [KAMI Blue]: Attempting KAMI Blue update check...
[05:31:07] [Client thread/INFO] [KAMI Blue]: Your KAMI Blue (v1.1.6) is up-to-date with the latest stable release.
[05:31:07] [Managers Pre-Loading/INFO] [KAMI Blue]: 6 managers found
[05:31:07] [Modules Pre-Loading/INFO] [KAMI Blue]: 160 modules found
Initializing KAMI Blue v1.1.7-b2448f04
[05:31:10] [Client thread/INFO] [KAMI Blue]: Rich Presence Users init!
[05:31:11] [Client thread/INFO] [KAMI Blue]: 160 modules loaded, took 886ms
[05:31:11] [KamiMoji Loading Thread/INFO] [KAMI Blue]: Initialising KamiMoji...
[05:31:11] [Client thread/INFO] [KAMI Blue]: 6 managers loaded, took 19ms
[05:31:11] [Client thread/INFO] [KAMI Blue]: Slick2D's TrueTypeFont renderer code was used in this mod
[05:31:11] [Client thread/INFO] [KAMI Blue]: Commands initialised
[05:31:11] [Macro Loading Thread/INFO] [KAMI Blue]: Macro loaded
[05:31:11] [Friend Loading Thread/INFO] [KAMI Blue]: Friend loaded

********** Missing Line !  **********   "Config loaded"

[05:31:11] [Waypoint Loading Thread/INFO] [KAMI Blue]: Waypoint loaded
[05:31:11] [Gui Loading Thread/INFO] [KAMI Blue]: Gui loaded
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: No enum constant me.zeroeightsix.kami.module.modules.combat.CrystalAura.Page.null
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Enum.valueOf(Enum.java:238)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.converter.EnumConverter.doBackward(EnumConverter.java:36)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.converter.EnumConverter.doBackward(EnumConverter.java:12)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.common.base.Converter.correctedDoBackward(Converter.java:185)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.common.base.Converter$ReverseConverter.correctedDoForward(Converter.java:269)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.google.common.base.Converter.convert(Converter.java:168)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:76)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:72)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:72)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:64)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:56)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.setting.config.Configuration.loadConfiguration(Configuration.java:50)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils.loadConfigurationUnsafe(ConfigUtils.kt:181)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils.loadConfiguration(ConfigUtils.kt:103)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils$loadAll$loadingThreads$4.run(ConfigUtils.kt:43)
[05:31:11] [Config Loading Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[05:31:11] [Client thread/INFO] [KAMI Blue]: Starting Discord RPC
[05:31:12] [Client thread/INFO] [KAMI Blue]: Discord RPC initialised successfully
[05:31:12] [Client thread/INFO] [KAMI Blue]: KAMI Blue Mod initialized!
[05:34:10] [Auto Saving Thread/INFO] [KAMI Blue]: Config saved

From the second run  (only the KAMI lines):

[05:42:50] [Client thread/INFO] [KAMI Blue]: Attempting KAMI Blue update check...
[05:42:50] [Client thread/INFO] [KAMI Blue]: Your KAMI Blue (v1.1.6) is up-to-date with the latest stable release.
[05:42:50] [Managers Pre-Loading/INFO] [KAMI Blue]: 6 managers found
[05:42:51] [Modules Pre-Loading/INFO] [KAMI Blue]: 160 modules found
[05:42:53] [Client thread/ERROR] [FML]: Exception loading model for variant kamiblue:kami_xray_transparent#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model kamiblue:item/kami_xray_transparent with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:161) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:302) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:175) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:151) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.io.FileNotFoundException: kamiblue:models/item/kami_xray_transparent.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) ~[cei.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[cev.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1400(ModelLoader.java:115) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:861) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) ~[ModelLoaderRegistry.class:?]
	... 22 more
[05:42:53] [Client thread/ERROR] [FML]: Exception loading model for variant kamiblue:kami_xray_transparent#inventory, blockstate location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model kamiblue:kami_xray_transparent#inventory with loader VariantLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:161) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:296) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:175) ~[cgb.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:151) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [cgc.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: net.minecraft.client.renderer.block.model.ModelBlockDefinition$MissingVariantException
	at net.minecraft.client.renderer.block.model.ModelBlockDefinition.func_188004_c(ModelBlockDefinition.java:83) ~[bvv.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1175) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:157) ~[ModelLoaderRegistry.class:?]
	... 22 more
[05:42:53] [Client thread/INFO] [KAMI Blue]: 

Initializing KAMI Blue v1.1.7-b2448f04
[05:42:54] [Client thread/INFO] [KAMI Blue]: Rich Presence Users init!
[05:42:54] [Client thread/INFO] [KAMI Blue]: 160 modules loaded, took 903ms
[05:42:54] [KamiMoji Loading Thread/INFO] [KAMI Blue]: Initialising KamiMoji...
[05:42:54] [Client thread/INFO] [KAMI Blue]: 6 managers loaded, took 21ms
[05:42:55] [Client thread/INFO] [KAMI Blue]: Slick2D's TrueTypeFont renderer code was used in this mod
[05:42:55] [Client thread/INFO] [KAMI Blue]: Commands initialised
[05:42:55] [Gui Loading Thread/INFO] [KAMI Blue]: Gui loaded
[05:42:55] [Macro Loading Thread/INFO] [KAMI Blue]: Macro loaded
[05:42:55] [Waypoint Loading Thread/INFO] [KAMI Blue]: Waypoint loaded
[05:42:55] [Friend Loading Thread/INFO] [KAMI Blue]: Friend loaded

**_[05:42:55] [Config Loading Thread/INFO] [KAMI Blue]: Config loaded_**

[05:42:55] [Client thread/INFO] [KAMI Blue]: Starting Discord RPC
[05:42:55] [Client thread/INFO] [KAMI Blue]: Discord RPC initialised successfully
[05:42:55] [Client thread/INFO] [KAMI Blue]: KAMI Blue Mod initialized!

So the problem happened in the initial run of the Minecraft, this morning.   Either it was unable to read, or it could not find the config file.

**Additional context**

Analysis:
1. I have been told the new .jar file could not have done this.
2. I have been told there is no single key I could have accidentally pressed to cause all KAMI/Blue settings to be erased.
3. I see that the KAMI config files, some of them have a time of 05:42.  

If 1. is true, and 2. is accepted then, I have to believe that KAMI/Blue believed my config files were not present, and created new ones.   This might be caused by a delay in my disk responding to a file inquiry, or a file error, or a bad sector on the drive.

**Comment by l1ving** [comment]
Are you sure it reset the enabled state and *not* the entire GUI position + module settings config?

**Comment by HoratioGamer** [comment]
I am certain it completely re-arranged my GUI "Player" "Movement" "Combat" etc, as well as my modules list and the dashboard, and changed all my settings.  The only thing that did not change was my ;m list.... I checked.

**Comment by l1ving** [comment]
Okay, then that makes much more sense. Macros are stored in a separate config. This means the auto-reset mechanism kicked in due to a previous value being invalid, and created a fresh config. 

I've personally never seen that mechanism actually work, even with invalid values. 

Now, what's *possible* is that removing modules caused it to throw an exception when trying to load module settings from modules that don't exist anymore, and caused an extreme edge case where it delets that config. 

**This has never happened in the past**, I want to absolutely *stress*, as we have never removed modules in the past (in this case we replaced them with new ones). 

This will be fixed by #1281 / #1358 and was entirely expected to be possible, but I never expected it to actually happen.

**Comment by HoratioGamer** [comment]
Mystery solved.

**Comment by l1ving** [comment]
Oh I didn't even read your log. Yea, now I can know for sure that was the reason. Removing enum *values* appears to trip it.

I fixed this in 3 different edge cases in the past, I guess I didn't consider what happens when entirely removing them

**Comment by l1ving** [comment]
Fixed in 56f5c4bdc8a382af591bdf6e0a5e0b7e120ac46c, edge cases shouldn't be possible anymore. Thanks!
