### ISSUE TITLE
Crash: No OpenGL context found in the current thread

### ISSUE THREAD

**Issue by ChillerDragon** [kami-blue/client#1451]
Tested with ba66ea680455132af97a9601dfaeec63b577c291, c45ffc50d984284d18e1db6f8fb1c039621dd53e and 30cfefb43d40e276f36eedee6cab596ff8970b69

Crash on launch. Using MultiMC on archlinux.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-1.1.7-beta-release.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/8/20 11:27 PM
Description: Initializing game

org.lwjgl.LWJGLException: X Error - disp: 0x7f9cd9099980 serial: 155 error: BadValue (integer parameter out of range for operation) request_code: 152 minor_code: 24
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.Display.create(Display.java:850)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.Display.create(Display.java:850)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.8.13-arch1-1
	Java Version: 1.8.0_265, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 587944336 bytes (560 MB) / 781713408 bytes (745 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-1.1.7-beta-release.jar)
  
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: fire (incompatible), weather (incompatible), bossbar (incompatible), transparentUI (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
```

**Comment by Xiaro** [comment]
Mojang code moment 🗿

**Comment by l1ving** [comment]
I need a full log file

**Comment by ChillerDragon** [comment]
This one? If not please halp me where to find it :)

<details>

```

MultiMC version: 0.6.11-custom


Minecraft folder is:
/home/chiller/.local/share/multimc/instances/1.12.2_forge/.minecraft


Java path is:
/usr/lib/jvm/java-8-openjdk/jre/bin/java


Java is version 1.8.0_265, using 64-bit architecture.


Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

Subsystem: Gigabyte Technology Co., Ltd Device d000

Kernel driver in use: i915

NVIDIA Corporation GM204 [GeForce GTX 980] (rev a1)

Subsystem: NVIDIA Corporation Device 1116

Kernel driver in use: nvidia

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  /home/chiller/.local/share/multimc/instances/1.12.2_forge/natives

Libraries:
  /home/chiller/.local/share/multimc/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  /home/chiller/.local/share/multimc/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /home/chiller/.local/share/multimc/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /home/chiller/.local/share/multimc/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /home/chiller/.local/share/multimc/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /home/chiller/.local/share/multimc/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  /home/chiller/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /home/chiller/.local/share/multimc/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  /home/chiller/.local/share/multimc/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  /home/chiller/.local/share/multimc/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  /home/chiller/.local/share/multimc/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  /home/chiller/.local/share/multimc/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  /home/chiller/.local/share/multimc/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  /home/chiller/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /home/chiller/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /home/chiller/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /home/chiller/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /home/chiller/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /home/chiller/.local/share/multimc/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  /home/chiller/.local/share/multimc/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-universal.jar
  /home/chiller/.local/share/multimc/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  /home/chiller/.local/share/multimc/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  /home/chiller/.local/share/multimc/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  /home/chiller/.local/share/multimc/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  /home/chiller/.local/share/multimc/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  /home/chiller/.local/share/multimc/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  /home/chiller/.local/share/multimc/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  /home/chiller/.local/share/multimc/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  /home/chiller/.local/share/multimc/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  /home/chiller/.local/share/multimc/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  /home/chiller/.local/share/multimc/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-linux.jar
  /home/chiller/.local/share/multimc/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-linux.jar

Mods:
  [✔️] kamiblue-1.1.7-beta-release
  [✔️] update

Params:
  --username  --version MultiMC5 --gameDir /home/chiller/.local/share/multimc/instances/1.12.2_forge/.minecraft --assetsDir /home/chiller/.local/share/multimc/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-Xms512m, -Xmx1024m, -Duser.language=en]


Minecraft process ID: 108734


Using onesix launcher.

[23:56:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:56:05] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[23:56:05] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_265, running on Linux:amd64:5.8.13-arch1-1, installed at /usr/lib/jvm/java-8-openjdk/jre
[23:56:05] [main/INFO] [FML]: Searching /home/chiller/.local/share/multimc/instances/1.12.2_forge/.minecraft/mods for mods
[23:56:05] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from kamiblue-1.1.7-beta-release.jar
[23:56:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:56:05] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/home/chiller/.local/share/multimc/instances/1.12.2_forge/.minecraft/mods/kamiblue-1.1.7-beta-release.jar Service=LaunchWrapper Env=CLIENT
[23:56:05] [main/WARN] [FML]: The coremod KAMIBlueMixinLoader (me.zeroeightsix.kami.mixin.MixinLoaderForge) is not signed!
[23:56:05] [main/INFO] [KAMI Blue]: KAMI Blue and Baritone mixins initializing...
[23:56:05] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[23:56:05] [main/ERROR] [mixin]: Mixin config mixins.kami.json does not specify "minVersion" property
[23:56:05] [main/ERROR] [mixin]: Mixin config mixins.baritone.json does not specify "minVersion" property
[23:56:05] [main/INFO] [KAMI Blue]: KAMI Blue and Baritone mixins initialised.
[23:56:05] [main/INFO] [KAMI Blue]: searge
[23:56:05] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:56:05] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:56:06] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:56:06] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:56:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:56:06] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[23:56:06] [main/ERROR] [mixin]: Mixin config mixins.kami.json does not specify "minVersion" property
[23:56:06] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@3ed0918d
[23:56:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:56:07] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:56:07] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[23:56:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:56:07] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[23:56:07] [main/WARN] [mixin]: @Mixin target net.minecraft.block.state.BlockStateContainer$StateImplementation is public in mixins.baritone.json:MixinStateImplementation and should be specified in value
[23:56:07] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:56:08] [Client thread/INFO] [minecraft/Minecraft]: Setting user: ZillyHuhn
[23:56:10] [Client thread/WARN] [minecraft/GameSettings]: Skipping bad option: lastServer:
[23:56:11] [Client thread/INFO] [minecraft/Minecraft]: LWJGL Version: 2.9.4
[23:56:11] [Client thread/ERROR] [minecraft/Minecraft]: Couldn't set pixel format
org.lwjgl.LWJGLException: X Error - disp: 0x7fd1f177ae90 serial: 95 error: BadValue (integer parameter out of range for operation) request_code: 152 minor_code: 24
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:850) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:625) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[23:56:12] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:save:3444]: Shutting down: saving KAMI configuration
[23:56:12] [Config Saving Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalStateException: KamiMod.getInstance() must not be null
[23:56:12] [Config Saving Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils.saveConfigurationUnsafe(ConfigUtils.kt:212)
[23:56:12] [Config Saving Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils.saveConfiguration(ConfigUtils.kt:120)
[23:56:12] [Config Saving Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.zeroeightsix.kami.util.ConfigUtils$saveAll$savingThreads$4.run(ConfigUtils.kt:81)
[23:56:12] [Config Saving Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Thread.run(Thread.java:748)
[23:56:12] [Waypoint Saving Thread/INFO] [KAMI Blue]: Waypoint saved
[23:56:12] [Macro Saving Thread/INFO] [KAMI Blue]: Macro saved
[23:56:12] [Friend Saving Thread/INFO] [KAMI Blue]: Friend saved
[23:56:12] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:save:3446]: Configuration saved.
[23:56:13] [Client thread/INFO] [KAMI Blue]: Rich Presence Users init!
[23:56:13] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  KAMIBlueMixinLoader (kamiblue-1.1.7-beta-release.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 10/8/20 11:56 PM
Description: Initializing game

org.lwjgl.LWJGLException: X Error - disp: 0x7fd1f177ae90 serial: 155 error: BadValue (integer parameter out of range for operation) request_code: 152 minor_code: 24
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.Display.create(Display.java:850)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.LinuxDisplay.globalErrorHandler(LinuxDisplay.java:320)
	at org.lwjgl.opengl.LinuxContextImplementation.nCreate(Native Method)
	at org.lwjgl.opengl.LinuxContextImplementation.create(LinuxContextImplementation.java:51)
	at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
	at org.lwjgl.opengl.Display.create(Display.java:850)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at net.minecraft.client.Minecraft.func_175609_am(Minecraft.java:645)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:458)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.8.13-arch1-1
	Java Version: 1.8.0_265, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 583841664 bytes (556 MB) / 780664832 bytes (744 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-1.1.7-beta-release.jar)
  
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: fire (incompatible), weather (incompatible), bossbar (incompatible), transparentUI (incompatible)
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
[23:56:13] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# /home/chiller/.local/share/multimc/instances/1.12.2_forge/.minecraft/crash-reports/crash-2020-10-08_23.56.13-client.txt
Exception in thread "Config Saving Thread" 
Process exited with code 255.
```
</details>

**Comment by l1ving** [comment]
This looks like something in Minecraft is calling GL from a thread that isn't the main thread. Does this happen to clean config? 

And when does this happen? in game or while loading?

and does this happen every time?

**Comment by ChillerDragon** [comment]
> This looks like something in Minecraft is calling GL from a thread that isn't the main thread. Does this happen to clean config?
> 
> And when does this happen? in game or while loading?
> 
> and does this happen every time?

On launch every time. This is my first time "using" the client. Since I never was able to start it I guess my config is default.

**Comment by ChillerDragon** [comment]
Omg im so sorry :/ I think it is a bug in my graphics driver.

**Comment by l1ving** [comment]
Launch the same multimc instance without kami blue and send the log

**Comment by l1ving** [comment]
> I was able to reproduce it in 602e8c4 already.

This is most definitely a YOU issue if it happens on a 2 year old version

**Comment by ChillerDragon** [comment]
Okay my assumptions was correct. Forgot that I did a update without reboot before and its the first time this caused minecraft to crash. Client launched fine now :)

sowwy for wasting your time guys and thanks for the fast response!
