### ISSUE TITLE
Auto Reconnect crashes kami

### ISSUE THREAD

**Issue by slashsynapse** [kami-blue/client#1500]
**Describe the bug**
so kami crashes the game with a ticking error?

**To Reproduce**
connect to a server, get yourself disconnected, then switch on auto reconnect and switch it off, and boom.

**Expected behavior**
for it to _not_ crash? 
 
**crash report**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinLoader (ElytraBot-2.1.jar)
  MixinLoaderForge (salhack-github-2.04-release.jar)
  ClsPlugin (CustomLoadingScreen-1.12.2-1.4.1.jar)
  KAMIBlueMixinLoader (kamiblue-1.1.7-beta-release.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 10/23/20 9:30 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at me.zeroeightsix.kami.module.modules.misc.AutoReconnect$KamiGuiDisconnected.func_73876_c(AutoReconnect.kt:44)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1779)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.zeroeightsix.kami.module.modules.misc.AutoReconnect$KamiGuiDisconnected.func_73876_c(AutoReconnect.kt:44)

-- Affected screen --
Details:
	Screen name: me.zeroeightsix.kami.module.modules.misc.AutoReconnect.KamiGuiDisconnected
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1779)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by l1ving** [comment]
```

java.lang.NullPointerException: Ticking screen
at me.zeroeightsix.kami.module.modules.misc.AutoReconnect$KamiGuiDisconnected.func_73876_c(AutoReconnect.kt:44)
```

please paste the full log on pastebin, and test without other mods installed

**Comment by slashsynapse** [comment]
https://pastebin.com/rsU5T6bC

**Comment by slashsynapse** [comment]
it does not happen only with kami blue, but it is a compatibility issue.

**Comment by l1ving** [comment]
>  ClsPlugin (CustomLoadingScreen-1.12.2-1.4.1.jar)

Bruh. Won't fix.
