### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hackerpri23** [kami-blue/client#2192]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from KAMI Blue (kamiblue)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (linux-aarch64/libdiscord-rpc.so) not found in resource path ([file:/storage/emulated/0/games/PojavLauncher/lwjgl3/jsr305.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-glfw-classes.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-jemalloc.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-openal.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-opengl.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-stb.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl-tinyfd.jar, file:/storage/emulated/0/games/PojavLauncher/lwjgl3/lwjgl.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/versions/1.12.2-forge-14.23.5.2854/1.12.2-forge-14.23.5.2854.jar, file:/storage/emulated/0/games/PojavLauncher/.minecraft/mods/kamiblue-2.04.01.jar, asmgen:/, file:/storage/emulated/0/games/PojavLauncher/.minecraft/mods/fabric-api-0.30.0+1.16.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:303)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Library$Handler.<init>(Library.java:179)
	at com.sun.jna.Native.loadLibrary(Native.java:569)
	at com.sun.jna.Native.loadLibrary(Native.java:544)
	at club.minnced.discord.rpc.DiscordRPC.<clinit>(DiscordRPC.java:42)
	at org.kamiblue.client.module.modules.misc.DiscordRPC.<clinit>(DiscordRPC.kt:44)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.kamiblue.commons.utils.ClassUtils.getInstance(ClassUtils.kt:27)
	at org.kamiblue.client.module.ModuleManager.load0(ModuleManager.kt:43)
	at org.kamiblue.client.module.ModuleManager.load0(ModuleManager.kt:16)
	at org.kamiblue.client.AsyncLoader$DefaultImpls.load(Loader.kt:49)
	at org.kamiblue.client.module.ModuleManager.load(ModuleManager.kt:16)
	at org.kamiblue.client.LoaderWrapper$loadAll$1.invokeSuspend(Loader.kt:32)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.kamiblue.client.LoaderWrapper.loadAll(Loader.kt:31)
	at org.kamiblue.client.KamiMod.init(KamiMod.kt:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (aarch64) version Android-10
	Java Version: 1.8.0-internal, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 861759616 bytes (821 MB) / 1291321344 bytes (1231 MB) up to 1291321344 bytes (1231 MB)
	JVM Flags: 3 total; -Xms1313M -Xmx1313M -Xbootclasspath/p:/storage/emulated/0/games/PojavLauncher/caciocavallo/ResConfHack.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-androidnw-1.10-SNAPSHOT.jar:/storage/emulated/0/games/PojavLauncher/caciocavallo/cacio-shared-1.10-SNAPSHOT.jar
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                        | Signature                                |
	|:----- |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHI  | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHI  | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| LCHI  | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge     | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHE  | kamiblue  | 2.04.01      | kamiblue-2.04.01.jar          | None                                     |

	Loaded coremods (and transformers): 
KAMIBlueMixinLoader (kamiblue-2.04.01.jar)
  
this is my error what to do?

**Comment by iBuyMountainDew** [comment]
The discord RPC libraries used by KAMI Blue don't work on ARM. Once they update, we'll follow suit.
